-- MATRICULA definition

CREATE TABLE MATRICULA
(
	IDMATRICULA INTEGER PRIMARY KEY NOT NULL,
	ATIVA BOOLEAN NOT NULL DEFAULT FALSE
);


-- PESSOA definition

CREATE TABLE PESSOA
(
	IDPESSOA INTEGER PRIMARY KEY NOT NULL,
	TIPO VARCHAR(40) NOT NULL,	
	NOME VARCHAR(100) NOT NULL,
	SENHA TEXT NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	EMAIL VARCHAR(45) NOT NULL,
	TELEFONE VARCHAR(11) NULL
);


-- CURSO definition

CREATE TABLE CURSO
(
	IDCURSO INTEGER PRIMARY KEY NOT NULL,
	NOME VARCHAR(60) NOT NULL,
	IDPESSOALANCAMENTO INTEGER NULL,
	FOREIGN KEY (IDPESSOALANCAMENTO) REFERENCES PESSOA (IDPESSOA)
);


-- EVENTO definition

CREATE TABLE EVENTO
(
	IDEVENTO INTEGER PRIMARY KEY NOT NULL,
	IDPESSOALANCAMENTO INTEGER NULL,
	DESCRICAO VARCHAR(40) NOT NULL,
	FOREIGN KEY (IDPESSOALANCAMENTO) REFERENCES PESSOA (IDPESSOA)
);


-- GRADE_CURSO definition

CREATE TABLE GRADE_CURSO
(
	IDGRADECURSO INTEGER PRIMARY KEY NOT NULL,
	IDCURSO INTEGER NOT NULL,
	IDPESSOALANCAMENTO INTEGER NULL,
	TOTALHORAS DECIMAL(5,2) NOT NULL,
	VALIDADEINICIO DATE NOT NULL,
	VALIDADETERMINO DATE NOT NULL,
	FOREIGN KEY (IDCURSO) REFERENCES CURSO (IDCURSO)	
	FOREIGN KEY (IDPESSOALANCAMENTO) REFERENCES PESSOA (IDPESSOA)
);


-- GRADE_EVENTO definition

CREATE TABLE GRADE_EVENTO
(
	IDGRADEEVENTO INTEGER NOT NULL,
	IDGRADECURSO INTEGER NOT NULL,
	IDEVENTO INTEGER NOT NULL,
	IDPESSOALANCAMENTO INTEGER NULL,
	MINIMOHORAS DECIMAL(5,2) NOT NULL,
	MAXIMOHORAS DECIMAL(5,2) NOT NULL,
	PRIMARY KEY (IDGRADEEVENTO, IDGRADECURSO, IDEVENTO),
	FOREIGN KEY (IDEVENTO) REFERENCES EVENTO (IDEVENTO),
	FOREIGN KEY (IDPESSOALANCAMENTO) REFERENCES PESSOA (IDPESSOA)
);


-- PESSOA_MATRICULA definition

CREATE TABLE PESSOA_MATRICULA
(
	IDMATRICULA INTEGER NOT NULL,
	IDPESSOA INTEGER NOT NULL,
	PRIMARY KEY (IDMATRICULA, IDPESSOA),
	FOREIGN KEY (IDMATRICULA) REFERENCES MATRICULA (IDMATRICULA),
	FOREIGN KEY (IDPESSOA) REFERENCES PESSOA (IDPESSOA)
);


-- TURMA definition

CREATE TABLE TURMA
(
	IDTURMA INTEGER PRIMARY KEY NOT NULL,
	IDGRADECURSO INTEGER NOT NULL,
	IDPESSOALANCAMENTO INTEGER NULL,
	NOME VARCHAR(60) NOT NULL,
	DATAINICIO DATE NOT NULL,
	DATATERMINO DATE NOT NULL,
	FOREIGN KEY (IDGRADECURSO) REFERENCES GRADE_CURSO (IDGRADECURSO),
	FOREIGN KEY (IDPESSOALANCAMENTO) REFERENCES PESSOA (IDPESSOA)	
);


-- ALUNO_TURMA definition

CREATE TABLE ALUNO_TURMA
(
	IDPESSOA INTEGER NOT NULL,
	IDTURMA INTEGER NOT NULL,
	PRIMARY KEY (IDPESSOA, IDTURMA),
	FOREIGN KEY (IDPESSOA) REFERENCES PESSOA (IDPESSOA),
	FOREIGN KEY (IDTURMA) REFERENCES TURMA (IDTURMA)
);


-- LANCAMENTO definition

CREATE TABLE LANCAMENTO
(
	IDLANCAMENTO INTEGER NOT NULL,
	IDPESSOA INTEGER NOT NULL,
	IDTURMA INTEGER NOT NULL,
	IDGRADEEVENTO INTEGER NOT NULL,
	IDPESSOALANCAMENTO INTEGER NULL,
	DATALANCAMENTO DATETIME NOT NULL,
	DATAINICIOEVENTO DATETIME NOT NULL,
	DATATERMINOEVENTO DATETIME NOT NULL,
	TOTALHORAS DECIMAL(5,2) NOT NULL,
	STATUS CHAR(1) NOT NULL,
	OBSERVACAO TEXT NULL,
	CAMINHOCERTIFICADOFRENTE VARCHAR(255) NOT NULL,
	CAMINHOCERTIFICADOVERSO VARCHAR(255) NULL,
	DATAARQUIVAMENTO DATETIME NULL,
	PRIMARY KEY (IDLANCAMENTO, IDPESSOA, IDTURMA, IDGRADEEVENTO),
	FOREIGN KEY (IDPESSOA) REFERENCES PESSOA (IDPESSOA),
	FOREIGN KEY (IDTURMA) REFERENCES TURMA (IDTURMA),
	FOREIGN KEY (IDGRADEEVENTO) REFERENCES GRADE_EVENTO (IDGRADEEVENTO),
	FOREIGN KEY (IDPESSOALANCAMENTO) REFERENCES PESSOA (IDPESSOA)	
);


-- PROFESSOR_TURMA definition

CREATE TABLE PROFESSOR_TURMA
(
	IDPESSOA INTEGER NOT NULL,
	IDTURMA INTEGER NOT NULL,
	PRIMARY KEY (IDPESSOA, IDTURMA),
	FOREIGN KEY (IDPESSOA) REFERENCES PESSOA (IDPESSOA),
	FOREIGN KEY (IDTURMA) REFERENCES TURMA (IDTURMA)
);